/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semi.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import semi.app.model.i_selectDAO;
import semi.app.model.incomeDAO;
import semi.app.model.incomeDTO;
import semi.app.model.s_selectDAO;
import semi.app.model.spendDAO;
import semi.app.model.spendDTO;

/**
 *
 * @author PARK YUJEONG
 */
public class AddGUI extends javax.swing.JFrame implements ActionListener{
    i_selectDAO i_s_dao=new i_selectDAO();
    s_selectDAO s_s_dao=new s_selectDAO();
    
    incomeDAO i_dao=new incomeDAO();
    spendDAO s_dao=new spendDAO();
    
    /**
     * Creates new form AddGUI
     */
    public AddGUI() {
        initComponents();
        init();
        addEvent();
        
        //콤보박스에 목록 불러오는 메서드
        add_cb_i();
        add_cb_s();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bt_Income = new javax.swing.JRadioButton();
        cb_Income_Kind = new javax.swing.JComboBox<>();
        lb_Kind = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_Income_Money = new javax.swing.JTextField();
        bt_Spend = new javax.swing.JRadioButton();
        cb_Spend_Kind = new javax.swing.JComboBox<>();
        lb_Kind2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_Spend_Money = new javax.swing.JTextField();
        bt_input = new javax.swing.JButton();
        bt_input_can = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("입력"));

        group.add(bt_Income);
        bt_Income.setText("수입");
        bt_Income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_IncomeActionPerformed(evt);
            }
        });

        lb_Kind.setText("항   목");

        jLabel5.setText("금   액");

        group.add(bt_Spend);
        bt_Spend.setText("지출");

        lb_Kind2.setText("항   목");

        jLabel4.setText("금   액");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lb_Kind2))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lb_Kind))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Income)
                    .addComponent(tf_Spend_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Spend_Kind, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Spend)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb_Income_Kind, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_Income_Money, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(bt_Income)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Income_Kind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Kind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Income_Money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bt_Spend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Kind2)
                    .addComponent(cb_Spend_Kind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Spend_Money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        bt_input.setText("등록");

        bt_input_can.setText("취소");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_input_can, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_input)
                    .addComponent(bt_input_can))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_IncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_IncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bt_Income;
    private javax.swing.JRadioButton bt_Spend;
    private javax.swing.JButton bt_input;
    private javax.swing.JButton bt_input_can;
    private javax.swing.JComboBox<String> cb_Income_Kind;
    private javax.swing.JComboBox<String> cb_Spend_Kind;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Kind;
    private javax.swing.JLabel lb_Kind2;
    private javax.swing.JTextField tf_Income_Money;
    private javax.swing.JTextField tf_Spend_Money;
    // End of variables declaration//GEN-END:variables

    private void addEvent() {
        bt_input.addActionListener(this);
        bt_input_can.addActionListener(this);
    }

    private void init() {
        //나만 닫히게
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    @Override
    public void actionPerformed(ActionEvent e){
        
        if(e.getSource()==bt_input){
            
            //유효성 검사
            if(bt_Income.isSelected()){
                try {
                    add_Income();
                    tf_Spend_Money.setText("");
                } catch (SQLException ex) {
                   ex.printStackTrace();
                }
            }else if(bt_Spend.isSelected()){
                try {
                    add_Spend();
                    tf_Income_Money.setText("");
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(this, "분류를 선택하세요");
            }
        }else if(e.getSource()==bt_input_can){
            this.dispose();
        }
            
    }//
    
    private void add_Income() throws SQLException{
        try {
            int i_cnt=cb_Income_Kind.getSelectedIndex();
            String money=tf_Income_Money.getText();
            
            if(money==null || money.isEmpty()){
                JOptionPane.showMessageDialog(this, "금액을 입력하세요");
            }
            
            int i_money=Integer.parseInt(money);
            
            incomeDTO dto=new incomeDTO();
            
            dto.setIncome_kind(i_cnt);
            dto.setI_money(i_money);
            int cnt=i_dao.insertIncome(dto);
            
            String msg="";
            if(cnt>0){
                msg="등록 성공";
                this.dispose();
            }else{
                msg="등록 실패";
            }
            
            JOptionPane.showMessageDialog(this, msg);
            tf_Income_Money.setText("");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    
    private void add_Spend()throws SQLException{
        try {
            int s_cnt=cb_Spend_Kind.getSelectedIndex();
            String money=tf_Spend_Money.getText();
            
            if(money==null || money.isEmpty()){
                JOptionPane.showMessageDialog(this, "금액을 입력하세요");
            }
            
            int s_money=Integer.parseInt(money);
            
            spendDTO dto=new spendDTO();
            
            dto.setSpend_kind(s_cnt);
            dto.setS_money(s_money);
            int cnt=s_dao.insertSpend(dto);
            
            String msg="";
            if(cnt>0){
                msg="등록 성공";
                this.dispose();
            }else{
                msg="등록 실패";
            }
            
            JOptionPane.showMessageDialog(this, msg);
            tf_Spend_Money.setText("");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    
    
    private void add_cb_i(){
        try {
            Vector<String> list1=i_s_dao.select_i_kind();
            DefaultComboBoxModel<String> cmodel = new DefaultComboBoxModel<>(list1);
            cb_Income_Kind.setModel(cmodel);
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }//add_Income
    
    private void add_cb_s(){
        try {
            Vector<String> list2=s_s_dao.select_s_kind();
            DefaultComboBoxModel<String> cmodel = new DefaultComboBoxModel<>(list2);
            cb_Spend_Kind.setModel(cmodel);
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }//add_Income
}
