/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semi.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import semi.member.model.memberDAO;
import semi.member.model.memberDTO;

/**
 *
 * @author PARK YUJEONG
 */
public class JoinMember extends javax.swing.JFrame implements ActionListener{
    public static final int MEMBER_REGISTER = 1;
    private LoginGUI loginGui;
    private memberDAO dao;
    private boolean duplicated;
    
    /**
     * Creates new form JoinMember
     */
    
    public JoinMember() {
        initComponents();
        init();
        addEvent();
    }
    
    public boolean isDuplicated() {
        return duplicated;
    }
    
    public void setDuplicated(boolean duplicated) {
        this.duplicated = duplicated;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_join_id = new javax.swing.JTextField();
        tf_pwd = new javax.swing.JPasswordField();
        bt_join = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        bt_check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("비밀번호");

        jLabel2.setText("이름");

        jLabel3.setText("아이디");

        tf_join_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_join_idActionPerformed(evt);
            }
        });

        bt_join.setText("회원가입");

        bt_cancel.setText("취소");

        bt_check.setText("중복확인");
        bt_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_join_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(tf_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_pwd))
                        .addGap(18, 18, 18)
                        .addComponent(bt_check))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bt_join)
                        .addGap(34, 34, 34)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_join_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_check))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_join)
                    .addComponent(bt_cancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_checkActionPerformed

    private void tf_join_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_join_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_join_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_check;
    private javax.swing.JButton bt_join;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    javax.swing.JTextField tf_join_id;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_pwd;
    // End of variables declaration//GEN-END:variables

    private void init() {
        dao=new memberDAO();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }
    
    private void addEvent() {
        bt_join.addActionListener(this);
        
        bt_cancel.addActionListener(this);
        bt_check.addActionListener(this);
    }

    
     @Override
     public void actionPerformed(ActionEvent e) {
         if(e.getSource()==bt_join){
             try{
                 register();
             }catch(SQLException ex){
                 ex.printStackTrace();
             }
         }else if(e.getSource()==bt_check){
//             idCheck f = new idCheck(this, tf_join_id.getText());
//             f.setVisible(true);
                subId s=new subId(this, tf_join_id.getText());
                s.setVisible(true);
         }else if(e.getSource()==bt_cancel){
             this.dispose();
         }
         
     }

     
    private void register() throws SQLException{
        String m_name=tf_name.getText();
        String m_join_id=tf_join_id.getText();
        String m_pwd=tf_pwd.getText();
        
        if(m_name==null || m_name.isEmpty()){
            JOptionPane.showMessageDialog(this, "이름을 입력하세요");
            tf_name.requestFocus();
            return;
        }else if(m_join_id==null || m_join_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요");
            tf_join_id.requestFocus();
            return;
        }else if(m_pwd==null || m_pwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요");
            tf_join_id.requestFocus();
            return;
        }else if(!duplicated){
            JOptionPane.showMessageDialog(this, "아이디 중복확인을 해주세요");
            bt_check.requestFocus();
            return;            
        }
        
        memberDTO dto=new memberDTO();
        dto.setM_name(m_name);
        dto.setM_id(m_join_id);
        dto.setM_pwd(m_pwd);
        
        int cnt=dao.insertMember(dto);        

        if(cnt>0){
            JOptionPane.showMessageDialog(this, "회원가입되었습니다.");
            this.dispose();
            
            
        }else{
            JOptionPane.showMessageDialog(this, "회원가입 실패");
        }
            
    }
   

}
