/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semi.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import semi.app.model.i_selectDAO;
import semi.app.model.i_selectDTO;
import semi.app.model.incomeDAO;
import semi.app.model.incomeDTO;
import semi.app.model.s_selectDAO;
import semi.app.model.s_selectDTO;
import semi.app.model.spendDAO;

/**
 *
 * @author PARK YUJEONG
 */
public class MainGUI extends javax.swing.JFrame implements ActionListener{
    private i_selectDAO i_s_dao;
    private s_selectDAO s_s_dao;
    
    private incomeDAO i_dao;
    private spendDAO s_dao;   
    
    public static int TABLE_SELECT=0;
    
    
    private String[] colNames={"번호", "항목", "금액", "등록시간"};
    private DefaultTableModel model_i = new DefaultTableModel();
    private DefaultTableModel model_s = new DefaultTableModel();
    
    private DefaultTableModel model_n = new DefaultTableModel();
    
    public MainGUI() throws SQLException{
        initComponents();
        init();
        addEvent();
        i_showData();
        s_showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bt_Logout = new javax.swing.JButton();
        bt_Exit = new javax.swing.JButton();
        panel_R = new javax.swing.JPanel();
        bt_Add = new javax.swing.JButton();
        bt_Del = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_Year = new javax.swing.JTextField();
        tf_Month = new javax.swing.JTextField();
        tf_Date = new javax.swing.JTextField();
        bt_Select = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_income = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_spend = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_Today = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bt_Logout.setText("로그아웃");
        bt_Logout.setFocusable(false);
        bt_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bt_Logout);

        bt_Exit.setText("종료");
        bt_Exit.setFocusable(false);
        bt_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bt_Exit);

        panel_R.setBorder(javax.swing.BorderFactory.createTitledBorder("오늘의 가계부"));

        bt_Add.setText("추가");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });

        bt_Del.setText("삭제");
        bt_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DelActionPerformed(evt);
            }
        });

        jLabel1.setText("년");

        jLabel2.setText("일");

        jLabel3.setText("월");

        bt_Select.setText("검색 및 새로고침");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tf_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_Select)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tf_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Select))
                .addContainerGap())
        );

        t_income.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "항목", "금액", "등록시간"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_income.setEnabled(false);
        t_income.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_incomeMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(t_income);

        t_spend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "항목", "금액", "등록시간"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_spend.setEnabled(false);
        t_spend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_spendMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(t_spend);

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("수입");

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("지출");

        javax.swing.GroupLayout panel_RLayout = new javax.swing.GroupLayout(panel_R);
        panel_R.setLayout(panel_RLayout);
        panel_RLayout.setHorizontalGroup(
            panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_RLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(bt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_RLayout.createSequentialGroup()
                        .addGroup(panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_RLayout.createSequentialGroup()
                                .addGroup(panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_RLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        panel_RLayout.setVerticalGroup(
            panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_RLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Add)
                    .addComponent(bt_Del))
                .addGap(8, 8, 8))
        );

        tf_Today.setEditable(false);
        tf_Today.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TodayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_Today, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_Today, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AddActionPerformed

    private void bt_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DelActionPerformed

    private void tf_TodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TodayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TodayActionPerformed

    private void t_incomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_incomeMousePressed

    }//GEN-LAST:event_t_incomeMousePressed

    private void t_spendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_spendMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_spendMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainGUI().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Del;
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Logout;
    private javax.swing.JButton bt_Select;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel_R;
    private javax.swing.JTable t_income;
    private javax.swing.JTable t_spend;
    private javax.swing.JTextField tf_Date;
    private javax.swing.JTextField tf_Month;
    private javax.swing.JTextField tf_Today;
    private javax.swing.JTextField tf_Year;
    // End of variables declaration//GEN-END:variables


    private void init(){
        i_s_dao=new i_selectDAO();
        s_s_dao=new s_selectDAO();
        
        i_dao=new incomeDAO();
        s_dao=new spendDAO();
        
        //tf Year, Month, Date에 오늘 날짜 set
        Calendar cal=Calendar.getInstance();
        
        SimpleDateFormat yyyy=new SimpleDateFormat("yyyy");
        SimpleDateFormat mm=new SimpleDateFormat("MM");
        SimpleDateFormat dd=new SimpleDateFormat("dd");
        
        String year=yyyy.format(cal.getTime());
        String month=mm.format(cal.getTime());
        String date=dd.format(cal.getTime());
        
        tf_Year.setText(year);
        tf_Month.setText(month);
        tf_Date.setText(date);
        
        SimpleDateFormat sdftoday=new SimpleDateFormat("yyyy년 MM월 dd일 E요일");
        String today=sdftoday.format(cal.getTime());
        tf_Today.setText(today);
        
    }
    
    
    private void addEvent() {
        bt_Exit.addActionListener(this);
        bt_Logout.addActionListener(this);
        
        bt_Select.addActionListener(this);
        bt_Add.addActionListener(this);       
        bt_Del.addActionListener(this);
        
        t_income.addMouseListener(new EventHandler());
        t_spend.addMouseListener(new EventHandler());
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
        //로그아웃, 종료
        if(e.getSource()==bt_Exit){
            System.exit(0);
        }else if(e.getSource()==bt_Logout){
            this.dispose();
            LoginGUI f=new LoginGUI();
            f.setVisible(true);
        }
        
        if(e.getSource()==bt_Add){
            AddGUI f=new AddGUI();
            f.setVisible(true);
            
        }else if(e.getSource()==bt_Del){
            DeleteGUI f=new DeleteGUI();
            f.setVisible(true);
        }
        
        //날짜 입력 유효성 검사
        String tfyear=tf_Year.getText();
        String tfmonth=tf_Month.getText();
        String tfdate=tf_Date.getText();
        
        int tfyear2=(Integer.parseInt(tfyear));
        int tfmonth2=(Integer.parseInt(tfmonth));
        int tfdate2=(Integer.parseInt(tfdate));
        
        if(e.getSource()==bt_Select){
            
            if(tfyear==null || tfyear.isEmpty()){
                JOptionPane.showMessageDialog(this, "연도를 입력하세요");
            }else if(tfmonth==null || tfmonth.isEmpty()){
                JOptionPane.showMessageDialog(this, "월을 입력하세요");
            }else if(tfdate==null || tfdate.isEmpty()){
                JOptionPane.showMessageDialog(this, "날짜를 입력하세요");
            }
            if(!(tfyear2>=2000 && tfyear2<=2025)){
                JOptionPane.showMessageDialog(this, "유효한 연도를 입력하세요 (2020~2025)");
            }else if(!(tfmonth2>=1 && tfmonth2<=12)){
                JOptionPane.showMessageDialog(this, "유효한 월을 입력하세요 (1~12)");
            }
            
            if(tfmonth2==2){
                if(!(tfdate2>=1 && tfdate2<=28)){
                    JOptionPane.showMessageDialog(this, "유효한 일을 입력하세요 (1~28)");
                }//
            }else if(tfmonth2%2==0 && tfmonth2!=2){
                if(!(tfdate2>=1 && tfdate2<=31)){
                    JOptionPane.showMessageDialog(this, "유효한 일을 입력하세요 (1~31)");
                }
            }else if(tfmonth2%2==1){
                if(!(tfdate2>=1 && tfdate2<=30)){
                    JOptionPane.showMessageDialog(this, "유효한 일을 입력하세요 (1~30)");
                }
            }
            
            if(e.getSource()==bt_Select){
                try {
                    i_showData();
                    s_showData();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }//showData//btselect
        
    }//actionperformed
    

    public void i_showData() throws SQLException{
        String regdate=tf_Year.getText()+"-"+tf_Month.getText()+"-"+tf_Date.getText();
            
        try{
            ArrayList<i_selectDTO> list=i_s_dao.incomeSelect(regdate);

            if(list==null || list.isEmpty()){
                JOptionPane.showMessageDialog(this, "수입 데이터가 존재하지 않습니다.");
                t_income.setModel(model_n);
                
                return;
            }

            String[][] data = new String[list.size()][colNames.length];
            DecimalFormat df = new DecimalFormat("#,###");
            SimpleDateFormat sdf = new SimpleDateFormat ( "a h시mm분");

            for(int i=0;i<list.size();i++){
                i_selectDTO dto=list.get(i);

                data[i][0]=dto.getNo()+"";
                data[i][1]=dto.getKind()+"";
                String money = df.format(dto.getMoney());
                data[i][2]=money;
                String time = sdf.format(dto.getRegdate());
                data[i][3]=time;
            }
            model_i.setDataVector(data, colNames);
            
            t_income.setModel(model_i);
            
            DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    public void s_showData() throws SQLException{
        String regdate=tf_Year.getText()+"-"+tf_Month.getText()+"-"+tf_Date.getText();
            
        try{
            ArrayList<s_selectDTO> list=s_s_dao.spendSelect(regdate);

            if(list==null || list.isEmpty()){
                JOptionPane.showMessageDialog(this, "지출 데이터가 존재하지 않습니다.");
                t_spend.setModel(model_n);
                return;
            }

            String[][] data = new String[list.size()][colNames.length];
            DecimalFormat df = new DecimalFormat("#,###");
            SimpleDateFormat sdf = new SimpleDateFormat ( "a h시mm분");

            for(int i=0;i<list.size();i++){
                s_selectDTO dto=list.get(i);

                data[i][0]=dto.getNo()+"";
                data[i][1]=dto.getKind()+"";
                String money = df.format(dto.getMoney());
                data[i][2]=money;
                String time = sdf.format(dto.getRegdate());
                data[i][3]=time;
            }
            model_s.setDataVector(data, colNames);
            
            t_spend.setModel(model_s);
            
            DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
            dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    class EventHandler extends MouseAdapter implements ItemListener, KeyListener{

        @Override
        public void mouseClicked(MouseEvent e) { 
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
           
        }

        @Override
        public void keyTyped(KeyEvent e) {
           
        }

        @Override
        public void keyPressed(KeyEvent e) {
           
        }

        @Override
        public void keyReleased(KeyEvent e) {
           
        }
    }
    
        
}//
   



