/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semi.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import semi.member.model.memberDAO;
import semi.member.model.memberService;

/**
 *
 * @author STU
 */
public class subId extends javax.swing.JFrame implements ActionListener{
    private JoinMember joinmember;
    private memberDAO dao;
    /**
     * Creates new form subId
     */
    public subId() {
        initComponents();
        
        init();
        addEvent();
    }

    public subId(JoinMember joinmember, String m_id) {
        this();
        
        this.joinmember = joinmember;
        tf_Id_Check.setText(m_id);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_Id_Check = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_check.setText("중복확인");

        jLabel1.setText("아이디");

        tf_Id_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Id_CheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_Id_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_check)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Id_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_check))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_Id_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Id_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Id_CheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_check;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField tf_Id_Check;
    // End of variables declaration//GEN-END:variables

    private void addEvent() {
        bt_check.addActionListener(this);
    }

    private void init() {
        dao=new memberDAO();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       if(e.getSource()==bt_check){
           try {
               checkDuplicate();
           } catch (SQLException ex) {
               ex.printStackTrace();
           }
       }
    }//
    
    private void checkDuplicate() throws SQLException{
        String m_id=tf_Id_Check.getText();
        if(m_id==null || m_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "아이디를 입력하세요");
            tf_Id_Check.requestFocus();
            return;
        }
        
        int result=dao.checkm_id(m_id);
        
         if(result==memberService.USABLE_ID){
            int type=JOptionPane.showConfirmDialog(this, "사용가능한 아이디입니다. 사용하시겠습니까?","아이디확인",
                    JOptionPane.YES_NO_OPTION);
            if(type==JOptionPane.YES_OPTION){
                //아이디를 회원가입화면에 출력해주고 창 닫기
                joinmember.tf_join_id.setText(m_id);
                joinmember.setDuplicated(true);  //아이디 중복확인을 했다는 표시
                this.dispose();
            }
         }else if(result==memberService.NONE_USABLE_ID){
              JOptionPane.showMessageDialog(this, "해당 아이디가 이미 존재합니다. 다른 아이디를 입력하세요");
         }else{
             JOptionPane.showMessageDialog(this, "아이디 중복확인에 실패했습니다");
         }
    }//
}
